on:
  release:
    types: [published]
  
  workflow_run:
    workflows: ["Scheduled Release"]
    types: [completed]

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:

      - name: Trigger echo
        run: echo "A new release has been published."
        
      - id: fetch-latest-release
        uses: thebritican/fetch-latest-release@v2.0.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  DeployProd:
    name: Trigger Jenkins Job on Prod
    runs-on: ubuntu-latest
    steps:
      - name: Set tag, client, and AWS env vars
        run: | 
          echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
          echo "CLIENT=standard" >> $GITHUB_ENV
          echo "AWS_DEFAULT_REGION=eu-west-1" >> $GITHUB_ENV
          echo "AWS_SG_ID=sg-0e5c105a5f7ad1e6e" >> $GITHUB_ENV
          
      - name: Jenkins Job Run
        uses: toptal/jenkins-job-trigger-action@master
        with:
              "Tag": "${{ env.TAG }}"
            
        
