name: Scheduled Release

on:
  schedule:
    # Runs "At according to cron schedule"
    - cron: '5 * * * *'

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: rymndhng/release-on-push-action@master
        with:
          # increments the patch version by 1. e.g. 1.0.0 > 1.0.1
          bump_version_scheme: patch
