name: Scheduled Release

on:
  push:

name: Scheduled Release

on:
  schedule:
    # To update the schedule, navigate to https://crontab.guru/. Here you can easily set the parameters for when the schedule should run. 
    # This is currently set to run at 4:00am every Tuesday.
    - cron: '0 4 * * 2'

env:
    Change_Freeze: false

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:

      - name: Change Freeze Implemented 
        if: env.Change_Freeze != 'false'
        run: echo "Scheduled Releases can only be published during approved maintenance windows."

      - name: Set env 
        if: env.Change_Freeze == 'false'
      - uses: rymndhng/release-on-push-action@master
        with:
          # increments the patch version by 1. e.g. 1.0.0 > 1.0.1
          bump_version_scheme: patch
          use_github_release_notes: true
          

