name: Scheduled Release

on:
  push:

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: rymndhng/release-on-push-action@master
        with:
          # increments the patch version by 1. e.g. 1.0.0 > 1.0.1
          bump_version_scheme: patch
          use_github_release_notes: true
          
      - name: Check Output Parameters
          run: |
            echo "Got tag name ${{ steps.release.outputs.tag_name }}"
            echo "Got release version ${{ steps.release.outputs.version }}"
