name: Scheduled Trigger

on:
  schedule:
    # Runs "Every 5 mins"
    - cron: '5 * * * *'

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: patch
