name: Publish Release
on:
  push
jobs:
  build:
    runs-on: ubuntu-latest
    env:
        GITHUB_TOKEN: ${{ secrets.actions }}
    steps:
    - name: Trigger echo
      run: echo "test"
    - uses: actions/checkout@v3
    - name: Create a Release
      uses: elgohr/Github-Release-Action@v4
      
      with:
        title: MyReleaseMessage
